insert into store_collection (id, title) values (1, 'Food - Pasta');
insert into store_collection (id, title) values (2, 'Food - Condiments');
insert into store_collection (id, title) values (3, 'Food - Baking');
insert into store_collection (id, title) values (4, 'Food - Produce');
insert into store_collection (id, title) values (5, 'Health');
insert into store_collection (id, title) values (6, 'Food - Condiments');
insert into store_collection (id, title) values (7, 'Electronics');
insert into store_collection (id, title) values (8, 'Footwear');
insert into store_collection (id, title) values (9, 'Kitchen');
insert into store_collection (id, title) values (10, 'Food - Snacks');
insert into store_collection (id, title) values (11, 'Food - Canned Goods');
insert into store_collection (id, title) values (12, 'Food - Produce');
insert into store_collection (id, title) values (13, 'Food - Seafood');
insert into store_collection (id, title) values (14, 'Food - Meat');
insert into store_collection (id, title) values (15, 'Food - Baking Goods');
insert into store_collection (id, title) values (16, 'Electronics');
insert into store_collection (id, title) values (17, 'Food - Snacks');
insert into store_collection (id, title) values (18, 'Food - Frozen Foods');
insert into store_collection (id, title) values (19, 'Food - Prepared Foods');
insert into store_collection (id, title) values (20, 'Clothing - Sweaters');
insert into store_collection (id, title) values (21, 'Food - Cooking Essentials');
insert into store_collection (id, title) values (22, 'Food - Fruits');
insert into store_collection (id, title) values (23, 'Food - Snacks');
insert into store_collection (id, title) values (24, 'Food - Frozen');
insert into store_collection (id, title) values (25, 'Food - Meat');
insert into store_collection (id, title) values (26, 'Clothing - Sweaters');
insert into store_collection (id, title) values (27, 'Food - Snacks');
insert into store_collection (id, title) values (28, 'Food - Condiments');
insert into store_collection (id, title) values (29, 'Footwear');
insert into store_collection (id, title) values (30, 'Outdoor');
insert into store_collection (id, title) values (31, 'Food - Baking');
insert into store_collection (id, title) values (32, 'Accessories');
insert into store_collection (id, title) values (33, 'Food - Canned Goods');
insert into store_collection (id, title) values (34, 'Food - Meat');
insert into store_collection (id, title) values (35, 'Food - Snacks');
insert into store_collection (id, title) values (36, 'Food - Grains');
insert into store_collection (id, title) values (37, 'Food - Dressing');
insert into store_collection (id, title) values (38, 'Food - Pasta');
insert into store_collection (id, title) values (39, 'Food - Frozen Foods');
insert into store_collection (id, title) values (40, 'Outdoor');
insert into store_collection (id, title) values (41, 'Food - Dairy');
insert into store_collection (id, title) values (42, 'Kitchen');
insert into store_collection (id, title) values (43, 'Toys');
insert into store_collection (id, title) values (44, 'Food - Bakery');
insert into store_collection (id, title) values (45, 'Food - Frozen Food');
insert into store_collection (id, title) values (46, 'Automotive');
insert into store_collection (id, title) values (47, 'Food - Meat Substitutes');
insert into store_collection (id, title) values (48, 'Food - Sauces');
insert into store_collection (id, title) values (49, 'Pets');
insert into store_collection (id, title) values (50, 'Food - Prepared Meals');
insert into store_collection (id, title) values (51, 'Clothing - Tops');
insert into store_collection (id, title) values (52, 'Food - Beverages');
insert into store_collection (id, title) values (53, 'Food - Dairy');
insert into store_collection (id, title) values (54, 'Kitchen');
insert into store_collection (id, title) values (55, 'Food - Bakery');
insert into store_collection (id, title) values (56, 'Food - Condiments');
insert into store_collection (id, title) values (57, 'Garden');
insert into store_collection (id, title) values (58, 'Pets');
insert into store_collection (id, title) values (59, 'Food - Baking');
insert into store_collection (id, title) values (60, 'Food - Frozen Foods');
insert into store_collection (id, title) values (61, 'Food - Grains');
insert into store_collection (id, title) values (62, 'Clothing - Sweaters');
insert into store_collection (id, title) values (63, 'Food - Meat');
insert into store_collection (id, title) values (64, 'Food - Bakery');
insert into store_collection (id, title) values (65, 'Food - Grains');
insert into store_collection (id, title) values (66, 'Food - Snacks');
insert into store_collection (id, title) values (67, 'Kitchen');
insert into store_collection (id, title) values (68, 'Food - Condiments');
insert into store_collection (id, title) values (69, 'Home');
insert into store_collection (id, title) values (70, 'Food - Breakfast');
insert into store_collection (id, title) values (71, 'Food - Pasta');
insert into store_collection (id, title) values (72, 'Automotive');
insert into store_collection (id, title) values (73, 'Food - Frozen Foods');
insert into store_collection (id, title) values (74, 'Food - Frozen Foods');
insert into store_collection (id, title) values (75, 'Home');
insert into store_collection (id, title) values (76, 'Food - Meat Substitutes');
insert into store_collection (id, title) values (77, 'Pets');
insert into store_collection (id, title) values (78, 'Garden');
insert into store_collection (id, title) values (79, 'Food - Snacks');
insert into store_collection (id, title) values (80, 'Food - Meat');
insert into store_collection (id, title) values (81, 'Electronics');
insert into store_collection (id, title) values (82, 'Fitness');
insert into store_collection (id, title) values (83, 'Food - Grains');
insert into store_collection (id, title) values (84, 'Food - Snacks');
insert into store_collection (id, title) values (85, 'Bicycles');
insert into store_collection (id, title) values (86, 'Food - Snacks');
insert into store_collection (id, title) values (87, 'Storage');
insert into store_collection (id, title) values (88, 'Clothing - Shirts');
insert into store_collection (id, title) values (89, 'Food - Frozen Foods');
insert into store_collection (id, title) values (90, 'Food - Beverages');
insert into store_collection (id, title) values (91, 'Food - Frozen');
insert into store_collection (id, title) values (92, 'Garden');
insert into store_collection (id, title) values (93, 'Accessories');
insert into store_collection (id, title) values (94, 'Health');
insert into store_collection (id, title) values (95, 'Outdoor');
insert into store_collection (id, title) values (96, 'Electronics');
insert into store_collection (id, title) values (97, 'Food - Meat');
insert into store_collection (id, title) values (98, 'Food - Canned Goods');
insert into store_collection (id, title) values (99, 'Health');
insert into store_collection (id, title) values (100, 'Food - Snacks');
insert into store_collection (id, title) values (101, 'Food - Cooking Essentials');
insert into store_collection (id, title) values (102, 'Home');
insert into store_collection (id, title) values (103, 'Pets');
insert into store_collection (id, title) values (104, 'Clothing - Tops');
insert into store_collection (id, title) values (105, 'Food - Frozen Meals');
insert into store_collection (id, title) values (106, 'Food - Prepared Foods');
insert into store_collection (id, title) values (107, 'Kitchen');
insert into store_collection (id, title) values (108, 'Kitchen');
insert into store_collection (id, title) values (109, 'Electronics');
insert into store_collection (id, title) values (110, 'Food - Condiments');
insert into store_collection (id, title) values (111, 'Food - Snacks');
insert into store_collection (id, title) values (112, 'Pets');
insert into store_collection (id, title) values (113, 'Food - Condiments');
insert into store_collection (id, title) values (114, 'Kitchen');
insert into store_collection (id, title) values (115, 'Food - Sauces');
insert into store_collection (id, title) values (116, 'Food - Breakfast');
insert into store_collection (id, title) values (117, 'Clothing - Swimwear');
insert into store_collection (id, title) values (118, 'Home');
insert into store_collection (id, title) values (119, 'Kitchen');
insert into store_collection (id, title) values (120, 'Food - Beverages');
insert into store_collection (id, title) values (121, 'Food - Nut Butters');
insert into store_collection (id, title) values (122, 'Food - Bakery');
insert into store_collection (id, title) values (123, 'Food - Prepared Meals');
insert into store_collection (id, title) values (124, 'Office');
insert into store_collection (id, title) values (125, 'Audio');
insert into store_collection (id, title) values (126, 'Food - Baking');
insert into store_collection (id, title) values (127, 'Food - Cereal');
insert into store_collection (id, title) values (128, 'Food - Spreads');
insert into store_collection (id, title) values (129, 'Accessories');
insert into store_collection (id, title) values (130, 'Kitchen');
insert into store_collection (id, title) values (131, 'Pets');
insert into store_collection (id, title) values (132, 'Fitness');
insert into store_collection (id, title) values (133, 'Home');
insert into store_collection (id, title) values (134, 'Food - Grains');
insert into store_collection (id, title) values (135, 'Food - Condiments');
insert into store_collection (id, title) values (136, 'Food - Dairy');
insert into store_collection (id, title) values (137, 'Accessories');
insert into store_collection (id, title) values (138, 'Home');
insert into store_collection (id, title) values (139, 'Food - Condiments');
insert into store_collection (id, title) values (140, 'Food - Spices');
insert into store_collection (id, title) values (141, 'Food - Produce');
insert into store_collection (id, title) values (142, 'Food - Fresh Produce');
insert into store_collection (id, title) values (143, 'Electronics');
insert into store_collection (id, title) values (144, 'Kitchen');
insert into store_collection (id, title) values (145, 'Food - Frozen');
insert into store_collection (id, title) values (146, 'Food - Prepared Foods');
insert into store_collection (id, title) values (147, 'Kitchen');
insert into store_collection (id, title) values (148, 'Toys');
insert into store_collection (id, title) values (149, 'Food - Condiments');
insert into store_collection (id, title) values (150, 'Fitness');
insert into store_collection (id, title) values (151, 'Food - Snacks');
insert into store_collection (id, title) values (152, 'Food - Meat');
insert into store_collection (id, title) values (153, 'Garden');
insert into store_collection (id, title) values (154, 'Kitchen');
insert into store_collection (id, title) values (155, 'Home');
insert into store_collection (id, title) values (156, 'Fitness');
insert into store_collection (id, title) values (157, 'Food - Condiments');
insert into store_collection (id, title) values (158, 'Food - Frozen Foods');
insert into store_collection (id, title) values (159, 'Accessories');
insert into store_collection (id, title) values (160, 'Outdoor');
insert into store_collection (id, title) values (161, 'Food - Frozen Meals');
insert into store_collection (id, title) values (162, 'Electronics');
insert into store_collection (id, title) values (163, 'Food - Oils & Vinegars');
insert into store_collection (id, title) values (164, 'Health');
insert into store_collection (id, title) values (165, 'Food - Dairy');
insert into store_collection (id, title) values (166, 'Food - Snacks');
insert into store_collection (id, title) values (167, 'Food - Fruits');
insert into store_collection (id, title) values (168, 'Kitchen');
insert into store_collection (id, title) values (169, 'Home');
insert into store_collection (id, title) values (170, 'Audio');
insert into store_collection (id, title) values (171, 'Food - Dairy');
insert into store_collection (id, title) values (172, 'Home');
insert into store_collection (id, title) values (173, 'Outdoor');
insert into store_collection (id, title) values (174, 'Food - Snacks');
insert into store_collection (id, title) values (175, 'Food - Snacks');
insert into store_collection (id, title) values (176, 'Travel');
insert into store_collection (id, title) values (177, 'Food - Household');
insert into store_collection (id, title) values (178, 'Audio');
insert into store_collection (id, title) values (179, 'Garden');
insert into store_collection (id, title) values (180, 'Food - Frozen');
insert into store_collection (id, title) values (181, 'Food - Prepared Meals');
insert into store_collection (id, title) values (182, 'Clothing - Dresses');
insert into store_collection (id, title) values (183, 'Outdoor');
insert into store_collection (id, title) values (184, 'Kitchen');
insert into store_collection (id, title) values (185, 'Food - Vegetables');
insert into store_collection (id, title) values (186, 'Gaming');
insert into store_collection (id, title) values (187, 'Home Appliances');
insert into store_collection (id, title) values (188, 'Food - Frozen Foods');
insert into store_collection (id, title) values (189, 'Food - Condiments');
insert into store_collection (id, title) values (190, 'Fitness');
insert into store_collection (id, title) values (191, 'Food - Snacks');
insert into store_collection (id, title) values (192, 'Food - Canned Goods');
insert into store_collection (id, title) values (193, 'Travel');
insert into store_collection (id, title) values (194, 'Food - Bakery');
insert into store_collection (id, title) values (195, 'Outdoor');
insert into store_collection (id, title) values (196, 'Art Supplies');
insert into store_collection (id, title) values (197, 'Food - Frozen Meals');
insert into store_collection (id, title) values (198, 'Automotive');
insert into store_collection (id, title) values (199, 'Clothing - Bottoms');
insert into store_collection (id, title) values (200, 'Food - Spices');
