# Generated by Django 5.2.10 on 2026-01-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        # Adding a new field to adress table named zip
        migrations.AddField(
            model_name='adress',
            name='zip',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
