# Generated by Django 5.2.10 on 2026-01-12 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL("""
                          INSERT INTO store_collection (title)
                          VALUES ('collection2');
                          """,
                          # This argument is opcional and alows you to reverse the migration if you fail with something
                          """
                          DELETE FROM store_collection WHERE title = 'collection2';
                          """)
    ]
